version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_KIBANA_VERSION
    restart: always
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.config.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ek

  kibana:
    build:
      context: kibana/
      args:
        KIBANA_VERSION: $ELASTIC_KIBANA_VERSION
    restart: always
    volumes:
      - type: bind
        source: ./kibana/kibana.config.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - ek
    depends_on:
      - elasticsearch

networks:
  ek:
    driver: bridge

volumes:
  esdata:
    driver: local
